
services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app/app:ro
      - ./tests:/app/tests:ro

  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  nginx:
    profiles:
      - production
